### ISSUE TITLE
libc++abi.dylib: Pure virtual function called!

### ISSUE THREAD

**Issue by mattpker** [TooTallNate/node-spotify-web#104]
Does anyone else get this error?

libc++abi.dylib: Pure virtual function called!

Occurs during playback, sometimes happens on the first song, sometime happens a few songs in. Seems very random and I cannot force it to happen. This happens if I am using headphones or the build-in speaker.

I am also sometimes getting "Segmentation Fault 11". I really want to be able to use this but is seems very buggy at this point.

OSX 10.10.1
Node v0.10.35

**Comment by mattpker** [comment]
It must be just my issue, ill close this.

**Comment by jeremywww** [comment]
I'm also getting these errors.

OSX 10.11
Node v0.12.2

**Comment by jarodreyes** [comment]
I also get this error
OSX 10.11
Node v6.3.0
