### ISSUE TITLE
Login failing - ECONNREFUSED

### ISSUE THREAD

**Issue by sciencepro** [TooTallNate/node-spotify-web#108]
Attempting login with known working credentials results in ECONNREFUSED

````
"code": "ECONNREFUSED",
"errno": "ECONNREFUSED",
"syscall": "connect"

**Comment by sciencepro** [comment]
Probably a duplicate of #102.  ping-pong.spotify.nodestuff.net appears down.  Time to learn how to run my own.

**Comment by vincentcox** [comment]
got the same problem. how do you fixed it?
Running the ping pong server locally (https://github.com/1994rstefan/Spotify-Ping-Pong-API) didn't worked
