### ISSUE TITLE
Login fails silently

### ISSUE THREAD

**Issue by filfat** [TooTallNate/node-spotify-web#117]
The callback from Spotify.login started to not get called this morning (though wrong username + password still errors as it should),

Is this a change on Spotify's end?

**Comment by pardo** [comment]
The spotify ping pong server may not be working , try setting it up locally,

https://github.com/1994rstefan/Spotify-Ping-Pong-API

**Comment by filfat** [comment]
@pardo it seems to work http://ping-pong.spotify.nodestuff.net/
I'll do some local testing shortly

**Comment by filfat** [comment]
@pardo Confirmed, it's not the ping pong server as it doesn't work locally either.

**Comment by filfat** [comment]
Wait a second, azure appears to fail to connect to http://ping-pong.spotify.nodestuff.net/ interesting.
I'll close this as it works if everything is locally.
