### ISSUE TITLE
Spotify Libraries Listing

### ISSUE THREAD

**Issue by hughrawlinson** [TooTallNate/node-spotify-web#132]
Hi,

Thanks for the awesome work on this library. I've listed it on [Spotify's list of 3rd party wrapper libraries](https://developer.spotify.com/web-api/code-examples/). Please feel free to ask me to remove it from the list, but I just wanted to let you know it's listed there now 😄 

Best,

Hugh
Spotify Developer Support

**Comment by denysvitali** [comment]
This API doesn't work anymore: the login is broken and playing music isn't possible due to the new Spotify MP3 Encryption. I don't know how this can be useful to someone

See #125, #118, #130 and related issues

**Comment by elribonazo** [comment]
@denysvitali , there's a version that is currently working, but you have to listen to the whole song to be able to stream, store or send it!

**Comment by denysvitali** [comment]
@elribonazo Which one? Can you link it? I'm pretty sure I've tried every fork of this repo

**Comment by hughrawlinson** [comment]
Ah, I misunderstood, I thought this was a wrapper library for the Spotify Web API.

**Comment by denysvitali** [comment]
Yep, it was, until Spotify introduced a captcha to stop this, and @TooTallNate stopped contribuiting to the project (due to Spotify decisions?)

**Comment by hughrawlinson** [comment]
@denysvitali - I mean the [Spotify Web API](https://github.com/spotify/web-api) rather than a private internal API for play.spotify.com.

**Comment by denysvitali** [comment]
@hughrawlinson Oh yes, sorry. Well, this project was a "self-made" API, created by reverse engineering Spotify Web. Personally I didn't even knew there was an official Spotify Web API before you pointed it out. Thanks!
