### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by bowilliams** [TooTallNate/node-spotify-web#87]
Starting this morning, I'm not able to login. I've tried several accounts (all premium). 

``` js
console.log('about to login');
Spotify.login(login.username, login.password, function (err, spotify) {
  console.log('logged in');
```

Never gets to logged in- it either hangs at about to login, or I get this error:

```
TypeError: Cannot read property 'version' of undefined
    at Spotify._resolveAP (/Users/bwilliams/repos/prosecco/local_spotify_player/node_modules/spotify-web/lib/spotify.js:306:50)
    at Spotify._onauth (/Users/bwilliams/repos/prosecco/local_spotify_player/node_modules/spotify-web/lib/spotify.js:294:10)
    at Request.callback (/Users/bwilliams/repos/prosecco/local_spotify_player/node_modules/spotify-web/node_modules/superagent/lib/node/index.js:584:30)
    at Request.<anonymous> (/Users/bwilliams/repos/prosecco/local_spotify_player/node_modules/spotify-web/node_modules/superagent/lib/node/index.js:133:10)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/bwilliams/repos/prosecco/local_spotify_player/node_modules/spotify-web/node_modules/superagent/lib/node/index.js:714:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

**Comment by Watiswat** [comment]
Login failed again... invalid username/password it says .. anyone?

**Comment by giacecco** [comment]
@Watiswat see https://github.com/TooTallNate/node-spotify-web/issues/102 .

**Comment by Watiswat** [comment]
@giacecco thanks, problem solved!

**Comment by jeffdran** [comment]
So, it seems that login isn't working for me anymore. I've been running my own pingpong server, and it says it's returning the pong ok, but still fails to login. Only have one pong worker if that helps.

I tried ping-pong.spotify.nodestuff.net, but seems to be down at the moment. Anyone else having issues?

**Comment by sciencepro** [comment]
Seeing similar issues with login via facebook or credentials.

**Comment by jeffdran** [comment]
It's just weird because it's not throwing any errors at all. Making it a little difficult to debug.

**Comment by sciencepro** [comment]
Yeah it's just spitting out a 403, I have not had the chance yet to dive in and see where it is failing.

**Comment by sciencepro** [comment]
@TooTallNate should there be a new issue for this, or re-open this one?  Will try to examine this further after my finals

**Comment by sciencepro** [comment]
Seems to be working again

**Comment by jeffdran** [comment]
Not working for me :/

**Comment by jeffdran** [comment]
Got it working with the server, but it's not working from local server.

**Comment by 1994rstefan** [comment]
Hello,
try to update the Flash-File on your local server.
________________________________
Von: jeffdran<mailto:notifications@github.com>
Gesendet: ‎06.‎05.‎2015 19:13
An: TooTallNate/node-spotify-web<mailto:node-spotify-web@noreply.github.com>
Cc: Stefan<mailto:stefan_1994@live.de>
Betreff: Re: [node-spotify-web] Login not working (#87)

Got it working with the server, but it's not working from local server.

---

**Comment by jeffdran** [comment]
Instead of making a new thread... anyone here experiencing "Track is not playable in country" issues? I can login fine, but cannot access track info. My assumption is they changed country codes to numbers.

**Comment by sciencepro** [comment]
@jeffdran Prior to updating to the latest commit, I was getting errors like

`````
{ [TrackError: Account subscription status not Spotify Premium]
  domain: 12,
  code: 0,
  description: '',
  data: null,
  name: 'TrackError',
  message: 'Account subscription status not Spotify Premium' }
````

After updating, I'm getting `Track is not playable in country`

**Comment by jeffdran** [comment]
@sciencepro I was getting the same issue until I updated. It's definitely recent, I had no problems about 2 days ago. I'll try looking into it either tonight or tomorrow morning.

**Comment by Watiswat** [comment]
i'm getting the same errors, has anyone worked on a fix yet?

**Comment by Watiswat** [comment]
@jeffdran I'm getting the same track error since a couple days, any clue what the problem might be?

**Comment by denysvitali** [comment]
Duplicate of #111

**Comment by ghost** [comment]
Hi Guys, I got this spotify music download about 6 months ago, it was working fine until now, any suggestions ??
